/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#dae2fd",
        "on-primary": "#ffffff",
        "tertiary-container": "#006e4b",
        "on-primary-fixed": "#0f0069",
        "on-primary-container": "#dad7ff",
        "on-tertiary-fixed": "#002113",
        "surface-tint": "#4d44e3",
        "on-secondary-fixed": "#131b2e",
        "on-surface": "#191c1e",
        "on-tertiary-container": "#67f4b7",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#bec6e0",
        "inverse-primary": "#c3c0ff",
        "on-background": "#191c1e",
        "on-error-container": "#93000a",
        "surface": "#F8FAFC",
        "surface-bright": "#F8FAFC",
        "primary-fixed-dim": "#c3c0ff",
        "primary-fixed": "#e2dfff",
        "inverse-on-surface": "#eff1f3",
        "outline-variant": "#c7c4d8",
        "on-tertiary-fixed-variant": "#005236",
        "tertiary-fixed": "#6ffbbe",
        "on-secondary-container": "#5c647a",
        "tertiary-fixed-dim": "#4edea3",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#464555",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#3f465c",
        "primary-container": "#4f46e5",
        "outline": "#777587",
        "secondary-container": "#dae2fd",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "background": "#F8FAFC",
        "secondary": "#565e74",
        "surface-container-low": "#f2f4f6",
        "surface-dim": "#d8dadc",
        "primary": "#4f46e5",
        "inverse-surface": "#2d3133",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#3323cc",
        "surface-container-highest": "#e0e3e5",
        "surface-variant": "#e0e3e5",
        "on-tertiary": "#ffffff",
        "surface-container": "#eceef0",
        "tertiary": "#005338"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "0.75rem",
        "xl": "1.25rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        "full": "9999px"
      },
      boxShadow: {
        'premium': '0 4px 6px -1px rgba(0, 0, 0, 0.02), 0 10px 15px -3px rgba(0, 0, 0, 0.03), 0 20px 25px -5px rgba(0, 0, 0, 0.02)',
        'premium-hover': '0 25px 50px -12px rgba(79, 70, 229, 0.12)',
        'inner-soft': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.03)',
      }
    },
  },
  plugins: [],
}
